#include <iostream>

extern int foo1();
extern int foo2();
extern int foo3();
extern int foo4();
extern int foo5();
extern int foo6();
extern int foo7();
extern int foo8();
extern int foo9();
extern int foo10();
extern int foo11();
extern int foo12();
extern int foo13();
extern int foo14();
extern int foo15();
extern int foo16();
extern int foo17();
extern int foo18();
extern int foo19();
extern int foo20();
extern int foo21();
extern int foo22();
extern int foo23();
extern int foo24();
extern int foo25();
extern int foo26();
extern int foo27();
extern int foo28();
extern int foo29();
extern int foo30();
extern int foo31();
extern int foo32();
extern int foo33();
extern int foo34();
extern int foo35();
extern int foo36();
extern int foo37();
extern int foo38();
extern int foo39();
extern int foo40();


int main() {
    std::cout << "Fun" << foo1() << std::endl;
    std::cout << "Fun" << foo2() << std::endl;
    std::cout << "Fun" << foo3() << std::endl;
    std::cout << "Fun" << foo4() << std::endl;
    std::cout << "Fun" << foo5() << std::endl;
    std::cout << "Fun" << foo6() << std::endl;
    std::cout << "Fun" << foo7() << std::endl;
    std::cout << "Fun" << foo8() << std::endl;
    std::cout << "Fun" << foo9() << std::endl;
    std::cout << "Fun" << foo10() << std::endl;
    std::cout << "Fun" << foo11() << std::endl;
    std::cout << "Fun" << foo12() << std::endl;
    std::cout << "Fun" << foo13() << std::endl;
    std::cout << "Fun" << foo14() << std::endl;
    std::cout << "Fun" << foo15() << std::endl;
    std::cout << "Fun" << foo16() << std::endl;
    std::cout << "Fun" << foo17() << std::endl;
    std::cout << "Fun" << foo18() << std::endl;
    std::cout << "Fun" << foo19() << std::endl;
    std::cout << "Fun" << foo20() << std::endl;
    std::cout << "Fun" << foo21() << std::endl;
    std::cout << "Fun" << foo22() << std::endl;
    std::cout << "Fun" << foo23() << std::endl;
    std::cout << "Fun" << foo24() << std::endl;
    std::cout << "Fun" << foo25() << std::endl;
    std::cout << "Fun" << foo26() << std::endl;
    std::cout << "Fun" << foo27() << std::endl;
    std::cout << "Fun" << foo28() << std::endl;
    std::cout << "Fun" << foo29() << std::endl;
    std::cout << "Fun" << foo30() << std::endl;
    std::cout << "Fun" << foo31() << std::endl;
    std::cout << "Fun" << foo32() << std::endl;
    std::cout << "Fun" << foo33() << std::endl;
    std::cout << "Fun" << foo34() << std::endl;
    std::cout << "Fun" << foo35() << std::endl;
    std::cout << "Fun" << foo36() << std::endl;
    std::cout << "Fun" << foo37() << std::endl;
    std::cout << "Fun" << foo38() << std::endl;
    std::cout << "Fun" << foo39() << std::endl;
    std::cout << "Fun" << foo40() << std::endl;
}
